#include <Arduino.h>

#include "stm32_gpio.h"

extern const int flash_size = 512 * 1024;

const stm32_port_pin_type variant_pin_list[] = {
  { GPIOA, GPIO_PIN_3 },
  { GPIOA, GPIO_PIN_2 },
  { GPIOA, GPIO_PIN_10},
  { GPIOB, GPIO_PIN_3 },
  { GPIOB, GPIO_PIN_5 },
  { GPIOB, GPIO_PIN_4 },
  { GPIOB, GPIO_PIN_10},
  { GPIOA, GPIO_PIN_8 },
  { GPIOA, GPIO_PIN_9 },
  { GPIOC, GPIO_PIN_7 },
  { GPIOB, GPIO_PIN_6 },
  { GPIOA, GPIO_PIN_7 },
  { GPIOA, GPIO_PIN_6 },
  { GPIOA, GPIO_PIN_5 },
  { GPIOB, GPIO_PIN_9 },
  { GPIOB, GPIO_PIN_8 },
  { GPIOA, GPIO_PIN_0 },
  { GPIOA, GPIO_PIN_1 },
  { GPIOA, GPIO_PIN_4 },
  { GPIOB, GPIO_PIN_0 },
  { GPIOC, GPIO_PIN_1 },
  { GPIOC, GPIO_PIN_0 },
  
  { GPIOA, GPIO_PIN_11},
  { GPIOA, GPIO_PIN_12},
  { GPIOA, GPIO_PIN_13},
  { GPIOA, GPIO_PIN_14},
  { GPIOA, GPIO_PIN_15},
  { GPIOB, GPIO_PIN_1 },
  { GPIOB, GPIO_PIN_2 },
  { GPIOB, GPIO_PIN_7 },
  { GPIOB, GPIO_PIN_12},
  { GPIOB, GPIO_PIN_13},
  { GPIOB, GPIO_PIN_14},
  { GPIOB, GPIO_PIN_15},
  { GPIOC, GPIO_PIN_2 },
  { GPIOC, GPIO_PIN_3 },
  { GPIOC, GPIO_PIN_4 },
  { GPIOC, GPIO_PIN_5 },
  { GPIOC, GPIO_PIN_6 },
  { GPIOC, GPIO_PIN_8 },
  { GPIOC, GPIO_PIN_9 },
  { GPIOC, GPIO_PIN_10},
  { GPIOC, GPIO_PIN_11},
  { GPIOC, GPIO_PIN_12},
  { GPIOC, GPIO_PIN_13},
  { GPIOC, GPIO_PIN_14},
  { GPIOC, GPIO_PIN_15},
  { GPIOD, GPIO_PIN_2 },
  #ifdef GPIOH
  { GPIOH, GPIO_PIN_0 },
  { GPIOH, GPIO_PIN_1 },
  #endif
};