//Autogenerated file
//MCU name: STM32L052C8
//MCU  xml: STM32L052C(6-8)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32L051_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_11.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_6.h"

#include "stm32_I2S_variant_1.h"

#include "stm32_LPUART_variant_6.h"

#include "stm32_SPI_variant_11.h"

#include "stm32_TIM_variant_9.h"

#include "stm32_USART_variant_8.h"

#include "stm32_ADC_variant_2.h"

#include "stm32_FREQ_variant_2.h"

