//Autogenerated file
//MCU name: STM32L072KB
//MCU  xml: STM32L072K(B-Z)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32L071_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_10.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_10.h"

#include "stm32_LPUART_variant_5.h"

#include "stm32_SPI_variant_12.h"

#include "stm32_TIM_variant_12.h"

#include "stm32_USART_variant_9.h"

#include "stm32_ADC_variant_2.h"

#include "stm32_FREQ_variant_6.h"

