//Autogenerated file
//MCU name: STM32L071VZ
//MCU  xml: STM32L071V(B-Z)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32L071_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_15.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_11.h"

#include "stm32_I2S_variant_3.h"

#include "stm32_LPUART_variant_10.h"

#include "stm32_SPI_variant_15.h"

#include "stm32_TIM_variant_15.h"

#include "stm32_USART_variant_12.h"

#include "stm32_ADC_variant_4.h"

#include "stm32_FREQ_variant_5.h"

