
const stm32_af_pin_list_type chip_af_lpuart_rx [] = {
//LPUART1
    { LPUART1, GPIOA, GPIO_PIN_3  , GPIO_AF6_LPUART1}, 
    { LPUART1, GPIOA, GPIO_PIN_13 , GPIO_AF6_LPUART1}, 
    { LPUART1, GPIOB, GPIO_PIN_10 , GPIO_AF7_LPUART1}, 
    { LPUART1, GPIOB, GPIO_PIN_11 , GPIO_AF4_LPUART1}, 
    { LPUART1, GPIOC, GPIO_PIN_0  , GPIO_AF6_LPUART1}, 
    { LPUART1, GPIOC, GPIO_PIN_5  , GPIO_AF2_LPUART1}, 
    { LPUART1, GPIOC, GPIO_PIN_11 , GPIO_AF0_LPUART1}, 
    { LPUART1, GPIOD, GPIO_PIN_9  , GPIO_AF0_LPUART1}, 
}; 

const stm32_af_pin_list_type chip_af_lpuart_tx [] = {
//LPUART1
    { LPUART1, GPIOA, GPIO_PIN_2  , GPIO_AF6_LPUART1}, 
    { LPUART1, GPIOA, GPIO_PIN_14 , GPIO_AF6_LPUART1}, 
    { LPUART1, GPIOB, GPIO_PIN_10 , GPIO_AF4_LPUART1}, 
    { LPUART1, GPIOB, GPIO_PIN_11 , GPIO_AF7_LPUART1}, 
    { LPUART1, GPIOC, GPIO_PIN_1  , GPIO_AF6_LPUART1}, 
    { LPUART1, GPIOC, GPIO_PIN_4  , GPIO_AF2_LPUART1}, 
    { LPUART1, GPIOC, GPIO_PIN_10 , GPIO_AF0_LPUART1}, 
    { LPUART1, GPIOD, GPIO_PIN_8  , GPIO_AF0_LPUART1}, 
}; 
