//Autogenerated file
//MCU name: STM32L021D4
//MCU  xml: STM32L021D4Px.xml
//GPIO remap/alternate function xml: GPIO-STM32L021_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_1.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_1.h"

#include "stm32_LPUART_variant_1.h"

#include "stm32_SPI_variant_1.h"

#include "stm32_TIM_variant_1.h"

#include "stm32_USART_variant_1.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_1.h"

