//Autogenerated file
//MCU name: STM32F479AI
//MCU  xml: STM32F479A(G-I)Hx.xml
//GPIO remap/alternate function xml: GPIO-STM32F469_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_16.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_13.h"

#include "stm32_I2S_variant_23.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_23.h"

#include "stm32_TIM_variant_22.h"

#include "stm32_USART_variant_26.h"

#include "stm32_ADC_variant_9.h"

#include "stm32_FREQ_variant_12.h"

