//Autogenerated file
//MCU name: STM32F479ZI
//MCU  xml: STM32F479Z(G-I)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F469_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_20.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_4.h"

#include "stm32_I2S_variant_26.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_27.h"

#include "stm32_TIM_variant_25.h"

#include "stm32_USART_variant_26.h"

#include "stm32_ADC_variant_7.h"

#include "stm32_FREQ_variant_9.h"

