//Autogenerated file
//MCU name: STM32F423ZH
//MCU  xml: STM32F423ZHTx.xml
//GPIO remap/alternate function xml: GPIO-STM32F413_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_7.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_FMPI2C_variant_7.h"

#include "stm32_I2C_variant_10.h"

#include "stm32_I2S_variant_18.h"

#include "stm32_SDIO_variant_5.h"

#include "stm32_SPI_variant_15.h"

#include "stm32_TIM_variant_15.h"

#include "stm32_USART_variant_19.h"

#include "stm32_ADC_variant_2.h"

#include "stm32_FREQ_variant_7.h"

