//Autogenerated file
//MCU name: STM32F423MH
//MCU  xml: STM32F423MHYx.xml
//GPIO remap/alternate function xml: GPIO-STM32F413_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_12.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_FMPI2C_variant_5.h"

#include "stm32_I2C_variant_9.h"

#include "stm32_I2S_variant_16.h"

#include "stm32_SDIO_variant_5.h"

#include "stm32_SPI_variant_13.h"

#include "stm32_TIM_variant_16.h"

#include "stm32_USART_variant_16.h"

#include "stm32_ADC_variant_2.h"

#include "stm32_FREQ_variant_7.h"

