//Autogenerated file
//MCU name: STM32F479NI
//MCU  xml: STM32F479N(G-I)Hx.xml
//GPIO remap/alternate function xml: GPIO-STM32F469_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_17.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_5.h"

#include "stm32_I2S_variant_24.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_24.h"

#include "stm32_TIM_variant_8.h"

#include "stm32_USART_variant_21.h"

#include "stm32_ADC_variant_5.h"

#include "stm32_FREQ_variant_8.h"

