//Autogenerated file
//MCU name: STM32F446VC
//MCU  xml: STM32F446V(C-E)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F446_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_3.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_FMPI2C_variant_10.h"

#include "stm32_I2C_variant_11.h"

#include "stm32_I2S_variant_22.h"

#include "stm32_SDIO_variant_6.h"

#include "stm32_SPI_variant_21.h"

#include "stm32_TIM_variant_20.h"

#include "stm32_USART_variant_24.h"

#include "stm32_ADC_variant_4.h"

#include "stm32_FREQ_variant_10.h"

