//Autogenerated file
//MCU name: STM32F412CE
//MCU  xml: STM32F412C(E-G)Ux.xml
//GPIO remap/alternate function xml: GPIO-STM32F412_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_1.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_FMPI2C_variant_4.h"

#include "stm32_I2C_variant_8.h"

#include "stm32_I2S_variant_12.h"

#include "stm32_SDIO_variant_4.h"

#include "stm32_SPI_variant_9.h"

#include "stm32_TIM_variant_12.h"

#include "stm32_USART_variant_11.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_7.h"

