//Autogenerated file
//MCU name: STM32F446ME
//MCU  xml: STM32F446M(C-E)Yx.xml
//GPIO remap/alternate function xml: GPIO-STM32F446_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_15.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_FMPI2C_variant_8.h"

#include "stm32_I2C_variant_11.h"

#include "stm32_I2S_variant_20.h"

#include "stm32_SDIO_variant_6.h"

#include "stm32_SPI_variant_19.h"

#include "stm32_TIM_variant_18.h"

#include "stm32_USART_variant_22.h"

#include "stm32_ADC_variant_8.h"

#include "stm32_FREQ_variant_10.h"

