//Autogenerated file
//MCU name: STM32F469II
//MCU  xml: STM32F469I(E-G-I)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F469_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_18.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_14.h"

#include "stm32_I2S_variant_25.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_25.h"

#include "stm32_TIM_variant_23.h"

#include "stm32_USART_variant_21.h"

#include "stm32_ADC_variant_5.h"

#include "stm32_FREQ_variant_8.h"

