
const stm32_af_pin_list_type chip_af_usart_rx [] = {
//UART4
    { UART4 , GPIOA, GPIO_PIN_1  , GPIO_AF8_UART4 }, 
    { UART4 , GPIOA, GPIO_PIN_11 , GPIO_AF11_UART4}, 
//UART5
    { UART5 , GPIOB, GPIO_PIN_5  , GPIO_AF11_UART5}, 
    { UART5 , GPIOB, GPIO_PIN_8  , GPIO_AF11_UART5}, 
    { UART5 , GPIOB, GPIO_PIN_12 , GPIO_AF11_UART5}, 
//UART7
    { UART7 , GPIOA, GPIO_PIN_8  , GPIO_AF8_UART7 }, 
    { UART7 , GPIOB, GPIO_PIN_3  , GPIO_AF8_UART7 }, 
//USART1
    { USART1, GPIOA, GPIO_PIN_10 , GPIO_AF7_USART1}, 
    { USART1, GPIOB, GPIO_PIN_3  , GPIO_AF7_USART1}, 
    { USART1, GPIOB, GPIO_PIN_7  , GPIO_AF7_USART1}, 
//USART2
    { USART2, GPIOA, GPIO_PIN_3  , GPIO_AF7_USART2}, 
//USART6
    { USART6, GPIOA, GPIO_PIN_12 , GPIO_AF8_USART6}, 
}; 

const stm32_af_pin_list_type chip_af_usart_tx [] = {
//UART4
    { UART4 , GPIOA, GPIO_PIN_0  , GPIO_AF8_UART4 }, 
    { UART4 , GPIOA, GPIO_PIN_12 , GPIO_AF11_UART4}, 
//UART5
    { UART5 , GPIOB, GPIO_PIN_6  , GPIO_AF11_UART5}, 
    { UART5 , GPIOB, GPIO_PIN_9  , GPIO_AF11_UART5}, 
    { UART5 , GPIOB, GPIO_PIN_13 , GPIO_AF11_UART5}, 
//UART7
    { UART7 , GPIOA, GPIO_PIN_15 , GPIO_AF8_UART7 }, 
    { UART7 , GPIOB, GPIO_PIN_4  , GPIO_AF8_UART7 }, 
//USART1
    { USART1, GPIOA, GPIO_PIN_9  , GPIO_AF7_USART1}, 
    { USART1, GPIOA, GPIO_PIN_15 , GPIO_AF7_USART1}, 
    { USART1, GPIOB, GPIO_PIN_6  , GPIO_AF7_USART1}, 
//USART2
    { USART2, GPIOA, GPIO_PIN_2  , GPIO_AF7_USART2}, 
//USART6
    { USART6, GPIOA, GPIO_PIN_11 , GPIO_AF8_USART6}, 
}; 
