//Autogenerated file
//MCU name: STM32F429ZG
//MCU  xml: STM32F429Z(E-G-I)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F427_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_7.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_4.h"

#include "stm32_I2S_variant_3.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_18.h"

#include "stm32_TIM_variant_7.h"

#include "stm32_USART_variant_21.h"

#include "stm32_ADC_variant_5.h"

#include "stm32_FREQ_variant_8.h"

