//Autogenerated file
//MCU name: STM32F410T8
//MCU  xml: STM32F410T(8-B)Yx.xml
//GPIO remap/alternate function xml: GPIO-STM32F410_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_11.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_FMPI2C_variant_3.h"

#include "stm32_I2C_variant_6.h"

#include "stm32_I2S_variant_8.h"

#include "stm32_SPI_variant_8.h"

#include "stm32_TIM_variant_11.h"

#include "stm32_USART_variant_9.h"

#include "stm32_ADC_variant_6.h"

#include "stm32_FREQ_variant_5.h"

