//Autogenerated file
//MCU name: STM32F439II
//MCU  xml: STM32F439I(G-I)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F427_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_8.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_5.h"

#include "stm32_I2S_variant_19.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_17.h"

#include "stm32_TIM_variant_8.h"

#include "stm32_USART_variant_21.h"

#include "stm32_ADC_variant_5.h"

#include "stm32_FREQ_variant_8.h"

