//Autogenerated file
//MCU name: STM32F767II
//MCU  xml: STM32F767I(G-I)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F76x_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_1.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_7.h"

#include "stm32_I2S_variant_6.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_10.h"

#include "stm32_TIM_variant_1.h"

#include "stm32_USART_variant_6.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_5.h"

