//Autogenerated file
//MCU name: STM32F746VG
//MCU  xml: STM32F746V(E-G)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F746_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_3.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_5.h"

#include "stm32_I2S_variant_3.h"

#include "stm32_SDIO_variant_2.h"

#include "stm32_SPI_variant_3.h"

#include "stm32_TIM_variant_3.h"

#include "stm32_USART_variant_3.h"

#include "stm32_ADC_variant_3.h"

#include "stm32_FREQ_variant_3.h"

