//Autogenerated file
//MCU name: STM32F723VC
//MCU  xml: STM32F723V(C-E)Yx.xml
//GPIO remap/alternate function xml: GPIO-STM32F72x_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_6.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_2.h"

#include "stm32_I2S_variant_5.h"

#include "stm32_SDIO_variant_2.h"

#include "stm32_SPI_variant_6.h"

#include "stm32_TIM_variant_6.h"

#include "stm32_USART_variant_5.h"

#include "stm32_ADC_variant_3.h"

#include "stm32_FREQ_variant_3.h"

