//Autogenerated file
//MCU name: STM32F378RC
//MCU  xml: STM32F378RCTx.xml
//GPIO remap/alternate function xml: GPIO-STM32F373_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_18.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_9.h"

#include "stm32_I2S_variant_8.h"

#include "stm32_SPI_variant_11.h"

#include "stm32_TIM_variant_18.h"

#include "stm32_USART_variant_10.h"

#include "stm32_ADC_variant_20.h"

#include "stm32_FREQ_variant_8.h"

