const stm32_chip_adc1_channel_type chip_adc1_channel[] = {
    { ADC1, GPIOA, GPIO_PIN_0  , ADC_CHANNEL_1  }, 
    { ADC1, GPIOA, GPIO_PIN_1  , ADC_CHANNEL_2  }, 
    { ADC1, GPIOA, GPIO_PIN_2  , ADC_CHANNEL_3  }, 
    { ADC1, GPIOA, GPIO_PIN_3  , ADC_CHANNEL_4  }, 
    { ADC1, GPIOA, GPIO_PIN_4  , ADC_CHANNEL_5  }, 
    { ADC1, GPIOA, GPIO_PIN_6  , ADC_CHANNEL_10 }, 
    { ADC1, GPIOB, GPIO_PIN_0  , ADC_CHANNEL_11 }, 
    { ADC1, GPIOB, GPIO_PIN_1  , ADC_CHANNEL_12 }, 
    { ADC1, GPIOB, GPIO_PIN_13 , ADC_CHANNEL_13 }, 
    { ADC1, GPIOB, GPIO_PIN_11 , ADC_CHANNEL_14 }, 
    { ADC1, GPIOA, GPIO_PIN_7  , ADC_CHANNEL_15 }, 
};
