//Autogenerated file
//MCU name: STM32F303RB
//MCU  xml: STM32F303R(B-C)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F303_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_4.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_4.h"

#include "stm32_I2S_variant_5.h"

#include "stm32_SPI_variant_5.h"

#include "stm32_TIM_variant_13.h"

#include "stm32_USART_variant_5.h"

#include "stm32_ADC_variant_14.h"

#include "stm32_FREQ_variant_3.h"

