//Autogenerated file
//MCU name: STM32F303VD
//MCU  xml: STM32F303V(D-E)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F303E_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_6.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_6.h"

#include "stm32_I2S_variant_6.h"

#include "stm32_SPI_variant_8.h"

#include "stm32_TIM_variant_16.h"

#include "stm32_USART_variant_8.h"

#include "stm32_ADC_variant_17.h"

#include "stm32_FREQ_variant_5.h"

