//Autogenerated file
//MCU name: STM32F303RE
//MCU  xml: STM32F303R(D-E)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F303E_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_3.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_3.h"

#include "stm32_I2S_variant_6.h"

#include "stm32_SPI_variant_6.h"

#include "stm32_TIM_variant_14.h"

#include "stm32_USART_variant_6.h"

#include "stm32_ADC_variant_15.h"

#include "stm32_FREQ_variant_4.h"

