//Autogenerated file
//MCU name: STM32F301R8
//MCU  xml: STM32F301R(6-8)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F302_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_3.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_3.h"

#include "stm32_I2S_variant_3.h"

#include "stm32_SPI_variant_3.h"

#include "stm32_TIM_variant_3.h"

#include "stm32_USART_variant_3.h"

#include "stm32_ADC_variant_3.h"

#include "stm32_FREQ_variant_1.h"

