//Autogenerated file
//MCU name: STM32L452CC
//MCU  xml: STM32L452C(C-E)Ux.xml
//GPIO remap/alternate function xml: GPIO-STM32L45x_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_1.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_4.h"

#include "stm32_LPUART_variant_1.h"

#include "stm32_SPI_variant_1.h"

#include "stm32_TIM_variant_4.h"

#include "stm32_USART_variant_5.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_3.h"

