//Autogenerated file
//MCU name: STM32L4A6QG
//MCU  xml: STM32L4A6QGIx.xml
//GPIO remap/alternate function xml: GPIO-STM32L49x_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_12.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_11.h"

#include "stm32_LPUART_variant_6.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_11.h"

#include "stm32_SWPMI_variant_1.h"

#include "stm32_TIM_variant_7.h"

#include "stm32_USART_variant_12.h"

#include "stm32_ADC_variant_3.h"

#include "stm32_FREQ_variant_3.h"

