//Autogenerated file
//MCU name: STM32L433RB
//MCU  xml: STM32L433R(B-C)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32L43x_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_3.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_3.h"

#include "stm32_LPUART_variant_3.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_3.h"

#include "stm32_SWPMI_variant_1.h"

#include "stm32_TIM_variant_1.h"

#include "stm32_USART_variant_3.h"

#include "stm32_ADC_variant_2.h"

#include "stm32_FREQ_variant_1.h"

