//Autogenerated file
//MCU name: STM32F103ZF
//MCU  xml: STM32F103Z(F-G)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F103xF_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_4.h"

#include "stm32_REMAP_variant_31.h"

#include "stm32_I2C_variant_2.h"

#include "stm32_I2S_variant_1.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_4.h"

#include "stm32_TIM_variant_31.h"

#include "stm32_USART_variant_6.h"

#include "stm32_ADC_variant_6.h"

#include "stm32_FREQ_variant_3.h"

