//Autogenerated file
//MCU name: STM32F105VB
//MCU  xml: STM32F105V(8-B-C)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F107_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_3.h"

#include "stm32_REMAP_variant_33.h"

#include "stm32_I2C_variant_2.h"

#include "stm32_I2S_variant_2.h"

#include "stm32_SPI_variant_5.h"

#include "stm32_TIM_variant_33.h"

#include "stm32_USART_variant_6.h"

#include "stm32_ADC_variant_4.h"

#include "stm32_FREQ_variant_4.h"

