//Autogenerated file
//MCU name: STM32F102C4
//MCU  xml: STM32F102C(4-6)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F103x4_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_1.h"

#include "stm32_REMAP_variant_8.h"

#include "stm32_I2C_variant_1.h"

#include "stm32_SPI_variant_1.h"

#include "stm32_TIM_variant_8.h"

#include "stm32_USART_variant_1.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_1.h"

