//Autogenerated file
//MCU name: STM32F205RE
//MCU  xml: STM32F205R(B-C-E-F-G)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32F217_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_1.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_1.h"

#include "stm32_I2S_variant_1.h"

#include "stm32_SDIO_variant_1.h"

#include "stm32_SPI_variant_1.h"

#include "stm32_TIM_variant_1.h"

#include "stm32_USART_variant_1.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_1.h"

