//Autogenerated file
//MCU name: STM32F042K4
//MCU  xml: STM32F042K(4-6)Ux.xml
//GPIO remap/alternate function xml: GPIO-STM32F042_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_18.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_15.h"

#include "stm32_I2S_variant_1.h"

#include "stm32_SPI_variant_5.h"

#include "stm32_TIM_variant_25.h"

#include "stm32_USART_variant_2.h"

#include "stm32_ADC_variant_1.h"

#include "stm32_FREQ_variant_4.h"

