//Autogenerated file
//MCU name: STM32F038F6
//MCU  xml: STM32F038F6Px.xml
//GPIO remap/alternate function xml: GPIO-STM32F031_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_22.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_4.h"

#include "stm32_I2S_variant_3.h"

#include "stm32_SPI_variant_4.h"

#include "stm32_TIM_variant_26.h"

#include "stm32_USART_variant_4.h"

#include "stm32_ADC_variant_4.h"

#include "stm32_FREQ_variant_1.h"

