//Autogenerated file
//MCU name: STM32L152V8
//MCU  xml: STM32L152V(8-B)Tx.xml
//GPIO remap/alternate function xml: GPIO-STM32L152x8_gpio_v1_0_Modes.xml


#include "stm32_GPIO_variant_4.h"

#include "stm32_REMAP_variant_1.h"

#include "stm32_I2C_variant_1.h"

#include "stm32_SPI_variant_5.h"

#include "stm32_TIM_variant_9.h"

#include "stm32_USART_variant_3.h"

#include "stm32_ADC_variant_4.h"

#include "stm32_FREQ_variant_1.h"

